config/routes.rb
Rails.application.routes.draw do
  resources :patients
  resources :appointments
  resources :doctors
  resources :insurance_cards, only: [:index]
  resources :hospitals, only: [:index, :show, :new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :hospital_categories
  has_many :hospitals, through: :hospital_categories
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments
  has_many :patients, through: :appointments

  has_many :hospitals
  # accepts_nested_attributes_for :hospitals

  def hospitals_attributes=(hospital_attributes)
    hospital_attributes.values.each do |hospital_attribute|
      hospital = Hospital.find_or_create_by(hospital_attribute)
      self.hospitals << hospital
    end
  end
end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
  belongs_to :doctor

  has_many :hospital_categories
  has_many :categories, through: :hospital_categories

  def category_ids=(ids)
    ids.each do |id|
      if id != ""
        category = Category.find(id)
        self.categories << category
      end
    end
  end
end

app/models/hospital_category.rb
class HospitalCategory < ActiveRecord::Base
  belongs_to :hospital
  belongs_to :category
end

app/models/insurance_card.rb
class InsuranceCard < ApplicationRecord
  has_many :patients

  # validates :patient_id, presence: true
  # validates :name, presence: true, length: { minimum: 4 }
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :insurance_card
  has_many :appointments
  has_many :doctors, through: :appointments

  def insurance_card_name=(name)
    self.insurance_card = InsuranceCard.find_or_create_by(name: name)
  end

  def insurance_card_name
    self.insurance_card.name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def new
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(apppointment_params)
    if @appointment.save
      redirect_to @appointment
    else
      render :new
    end
  end

  def show
    @appointment = Appointment.find(params[:id])
  end

  def index
    @appointments = Appointment.all
  end

  private

  def apppointment_params
    params.require(:appointment).permit(:month, :day, :doctor_id, :patient_id)
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def index
    @doctors = Doctor.all
  end

  def show
    @doctor = Doctor.find(params[:id])
  end

  def new
    @doctor = Doctor.new
    @doctor.hospitals.build
  end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      redirect_to @doctor
    else
      render :new
    end
  end

  private

  def doctor_params
    params.require(:doctor).permit(:name, :experience, hospitals_attributes: [:name, :years_worked, :area])
  end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  def index
    @hospitals = Hospital.all
  end

  def show
    @hospital = Hospital.find(params[:id])
  end

  def new
    @hospital = Hospital.new
  end

  def create
    @hospital = Hospital.create(hospital_params)      
    redirect_to @hospital
  end

  private

  def hospital_params
    params.require(:hospital).permit(:name, :years_worked, :area, :doctor_id, category_ids: [])
  end
end

app/controllers/insurance_cards_controller.rb
class InsuranceCardsController < ApplicationController
  def index
    @insurance_cards = InsuranceCard.all
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @patients = Patient.all
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      flash[:success] = "Welcome to the Health App!"
      redirect_to @patient
    else
      render :new
    end
  end

  private

    def patient_params
      params.require(:patient).permit(:name, :age, :insurance_card_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/index.html.erb
<h1>Appointments</h1>

<% @appointments.each do |appointment| %>
  <%= link_to 'View Details', appointment_path(appointment.id) %>
  <br>
  Date: <%= appointment.month %>, <%= appointment.day %>
  <br>
  Doctor: <%= appointment.doctor.name %>
  <br>
  Patient: <%= appointment.patient.name %>
  <hr>
<% end %>

app/views/appointments/new.html.erb
<h1>New Appointment Form</h1>

<%= form_for @appointment do |f| %>
  <%= f.label :month %>:
  <%= f.text_field :month %>
  <br>
  <%= f.label :day %>:
  <%= f.number_field :day %>
  <br>
  Doctor: <%= f.collection_select :doctor_id, Doctor.all, :id, :name %>
  <br>
  Patient: <%= f.collection_select :patient_id, Patient.all, :id, :name %>
  <br>
  <%= f.submit %>
<% end %>

app/views/appointments/show.html.erb
<h1>Appointment</h1>

Date: <%= @appointment.month %>, <%= @appointment.day %>
<br>
Doctor: <%= @appointment.doctor.name %>
<br>
Patient: <%= @appointment.patient.name %>

app/views/doctors/index.html.erb
<h1>Doctors</h1>
<hr>
<% @doctors.each do |doctor| %>
  <h4>Name: <%= doctor.name %></h4>
  <p><%= link_to 'See more information', doctor_path(doctor) %></p>

  <hr>
<% end %>

app/views/doctors/new.html.erb
<h1>Create a New Doctor with Hospital</h1>

<%= form_for @doctor do |f| %>
  <h4>Doctor Information</h4>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :experience %>
  <%= f.number_field :experience %>
  <br>
  <h4>Hospital Information</h4>
  <%= f.fields_for :hospitals do |hospital_form| %>
    <%= hospital_form.label :name %>
    <%= hospital_form.text_field :name %>
    <br>
    <%= hospital_form.label :years_worked %>
    <%= hospital_form.number_field :years_worked %>
    <br>
    <%= hospital_form.label :area %>
    <%= hospital_form.text_field :area %>
  <% end %>
  <br>
  <%= f.submit %>
<% end %>

app/views/doctors/show.html.erb
<h1>Doctor</h1>
<hr>
<h4>Name: <%= @doctor.name %></h4>
<p>Experience: <%= @doctor.experience %> year(s)</p>
<hr>
<p>Number of Appointments: <%= @doctor.appointments.count %></p>
<p>
  <% @doctor.appointments.each_with_index do |appointment, index| %>
    Appointment No. <%= index + 1 %> - Date: <%= appointment.month %> <%= appointment.day %><br>
  <% end %>
</p>
<p>Hospital Information:</p>
<p>
  <% @doctor.hospitals.each do |hospital| %>
    <%= hospital.name %>
  <% end %>
</p>

app/views/hospitals/index.html.erb
<h1>Hospitals</h1>

<% @hospitals.each do |hospital| %>
  <p><%= link_to hospital.name, hospital_path(hospital.id) %></p>
<% end %>

app/views/hospitals/new.html.erb
<h1>Create a New Hospital with Cateogies</h1>

<%= form_for @hospital do |f| %>
  <%= f.label "Name" %>
  <%= f.text_field :name %>
  <br>
  <%= f.label "Years Worked" %>
  <%= f.number_field :years_worked %>
  <br>
  <%= f.label "Area" %>
  <%= f.text_field :area %>
  <%= f.hidden_field :doctor_id, value: 1 %>
  <h4>Categories</h4>
  <%= f.label "Select One or More Category"%><br>
  <%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>
  <br>
  <%= f.submit %>
<% end %>

app/views/hospitals/show.html.erb
<h1>Hospital</h1>

<h4><%= @hospital.name %></h4>

<ul>
  <% @hospital.categories.each do |category| %>
    <li><%= category.name %></li>
  <% end %>
</ul>

app/views/insurance_cards/index.html.erb
<h1>Insurance Cards</h1>

<% @insurance_cards.each do |card| %>
  <h4><%= card.name %></h4>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FormsRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/index.html.erb
<% provide(:title, 'All Patients') %>

<h1>Patients</h1>

<hr>
<% @patients.each do |patient| %>
  <h4>Name: <%= patient.name %></h4>
  <p>-- <%= link_to 'See more information', patient_path(patient) %></p>

  <hr>
<% end %>

<br>
-- <%= link_to 'Create a new Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>Create a new Patient</h1>

<%= form_for @patient do |f| %>

  <div>
    <%= f.label :name %>: 
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :age %>: 
    <%= f.number_field :age %>
  </div>
  <br>
  <div>
    Patient Insurance Card Information:<br>
    <select name="patient[insurance_card_name]">
      <% InsuranceCard.all.each do |card| %>
        <option value="<%= card.name %>"><%= card.name %></option>
      <% end %>
    </select>
  </div>
  <br>
  
  <p><%= f.submit %></p>
<% end %>

app/views/patients/show.html.erb
<h1>Patient</h1>

<% flash.each do |message_type, message| %>
  <div><%= message %></div>
<% end %>

<h4>Patient Information</h4>
<p>Name: <%= @patient.name %></p>
<p>Age: <%= @patient.age %></p>
<br>

<h4>Patient Insurance Cards</h4>
<p><%= @patient.insurance_card.name %></p>

app/views/shared/_error_messages_patient.html.erb
<% if @patient.errors.any? %>
  <div id="error_explaination">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@patient.errors.count, "error") %>.
    </div>
    <ul>
      <% @patient.errors.full_message.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>